### ISSUE TITLE
Error when creating full report

### ISSUE THREAD

**Issue by innocenzi** [OsandaMalith/ChromeFreak#3]
Hey,

I got an error when I tried to generate a full report.
Here it is:

```
Traceback (most recent call last):
  File "<string>", line 412, in <module>
  File "<string>", line 399, in main
  File "<string>", line 389, in menu
  File "<string>", line 355, in banner
  File "<string>", line 248, in fullReport
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe7' in position 71: ordinal not in range(128)
```

Skype is closed and I've the right on the main.db.

**Comment by OsandaMalith** [comment]
I guess the issue is with encoding. I'll see to it Thanks!
